name: Data_Pipeline_CI_Check

on:
  pull_request:
    branches: [main]

jobs:
  simple_check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dbt only
        run: pip install dbt-bigquery

      - name: Run dbt Parse
        run: |
          cd include/dbt/oms_dbt_proj
          
          # Cipta file dummy supaya dbt diam
          echo "{}" > dummy.json
          echo "oms_dbt_proj:
            outputs:
              dev:
                type: bigquery
                method: service-account
                project: dummy
                dataset: dummy
                threads: 1
                keyfile: dummy.json
            target: dev" > profiles.yml