name: Enterprise_Data_Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # --- STAGE 1: CI (Continuous Integration) ---
  run_tests:
    runs-on: ubuntu-latest
    env:
      # Menyelaraskan nama env dengan medallion_1.py
      GCP_PROJECT_ID: "transactions-practice"
      GCP_DATASET_BRONZE: "bronze"
      GCP_LOCATION: "asia-southeast1"
      IS_PRODUCTION: "false"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Airflow DAG Integrity Test
        run: pytest tests/test_dag_integrity.py

      - name: dbt Compile Check
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          cd include/dbt/oms_dbt_proj
          
          # Gunakan printf untuk memastikan format JSON tidak rosak
          printf "%s" "$GCP_SA_KEY" > gcp-key.json
          
          # Memberitahu library Google secara global lokasi fail kunci
          export GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/gcp-key.json
          
          dbt deps
          # Menambah target dev secara eksplisit untuk dbt CLI
          dbt compile --profiles-dir . --target dev
          
          # Padam kunci selepas selesai
          rm gcp-key.json

  # --- STAGE 2: CD (Continuous Deployment) ---
  deploy_prod:
    needs: run_tests
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      GCP_PROJECT_ID: "transactions-practice"
      GCP_DATASET_BRONZE: "bronze"
      GCP_LOCATION: "asia-southeast1"
      IS_PRODUCTION: "true"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dbt
        run: pip install dbt-bigquery

      - name: Deploy to BigQuery Production
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          cd include/dbt/oms_dbt_proj
          
          printf "%s" "$GCP_SA_KEY" > gcp-key.json
          export GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/gcp-key.json
          
          dbt deps
          # Menjalankan transformasi sebenar
          dbt run --target dev --profiles-dir .
          
          rm gcp-key.json